.only-default: &only-default
  only:
    - api
    - web
    - main

include:
  - project: 'affinidi/foundational/foundational-pipeline'
    file: '/security.yml'

stages:
  - install
  - build
  - security-testing
  - deploy

install:
  <<: *only-default
  stage: install
  image: node
  cache:
    paths:
      - node_modules/
  artifacts:
    paths:
      - node_modules/
  script:
    - echo "Install project dependecies"
    - npm install
    - echo "Install successful"

build:
  <<: *only-default
  stage: build
  image: node
  script:
    - echo "Build started"
    - export REACT_APP_API_KEY_HASH=$REACT_APP_API_KEY_HASH
    - npm run build
    - echo "Build successfull"
  artifacts:
    paths:
      - build/

deploy:
  <<: *only-default
  stage: deploy
  dependencies:
    - build
  image:
    name: amazon/aws-cli
    entrypoint: ['']
  script:
    - aws s3 cp build/ s3://$S3_BUCKET/ --recursive
